#!/usr/bin/env python3
"""Print a markdown catalog of every registered MCP tool.

Pulls schemas live from GeneralToolRegistry / PCBToolRegistry (the same
source generate_dataset.py uses) so the catalog embedded in data/README.md
can never drift from the actual tool_defs.py definitions. Re-run this and
paste the output into data/README.md whenever a tool is added, removed, or
its schema changes:

    python3 data/tool_calling_sft/print_tool_catalog.py
"""

from __future__ import annotations

import sys
import types
from pathlib import Path

try:
    import cv2  # noqa: F401
except ImportError:
    sys.modules.setdefault("cv2", types.ModuleType("cv2"))

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from agents.mcp.domains.general.tool_defs import GeneralToolRegistry  # noqa: E402
from agents.mcp.domains.pcb.tool_defs import PCBToolRegistry  # noqa: E402
from agents.mcp.schema import MCPSchemaType  # noqa: E402


def render_param_row(p) -> str:
    type_str = p.type.value
    if p.enum:
        type_str += f" (`{'` / `'.join(p.enum)}`)"
    if p.type == MCPSchemaType.ARRAY and p.items_type:
        type_str = f"array of {p.items_type.value}"
    required = "yes" if p.required else "no"
    default = f"`{p.default}`" if p.default is not None else "—"
    desc = p.description
    if p.min_value is not None or p.max_value is not None:
        desc += f" (range: {p.min_value if p.min_value is not None else '−∞'}–{p.max_value if p.max_value is not None else '∞'})"
    if p.max_length is not None:
        desc += f" (max length: {p.max_length})"
    return f"| `{p.name}` | {type_str} | {required} | {default} | {desc} |"


def render_tool(tool) -> str:
    lines = [
        f"#### `{tool.name}`",
        "",
        f"*Category: `{tool.category}`* · *Requires confirmation: {'yes' if tool.requires_confirmation else 'no'}*",
        "",
        tool.description,
        "",
    ]
    if tool.input_schema:
        lines += [
            "| Parameter | Type | Required | Default | Description |",
            "|---|---|---|---|---|",
        ]
        lines += [render_param_row(p) for p in tool.input_schema]
    else:
        lines.append("*No parameters.*")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    general = GeneralToolRegistry().list_tools()
    pcb = PCBToolRegistry().list_tools()

    print(f"<!-- AUTO-GENERATED by data/tool_calling_sft/print_tool_catalog.py — do not hand-edit. -->")
    print(f"<!-- {len(general)} general-domain tools, {len(pcb)} PCB-domain tools, {len(general) + len(pcb)} total. -->")
    print()
    print("### General domain (%d tools)" % len(general))
    print()
    for t in sorted(general, key=lambda t: t.name):
        print(render_tool(t))
    print("### PCB domain (%d tools)" % len(pcb))
    print()
    for t in sorted(pcb, key=lambda t: t.name):
        print(render_tool(t))


if __name__ == "__main__":
    main()
